# Generated by Django 5.0.1 on 2024-01-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('movies_name', models.CharField(default='', max_length=150)),
                ('movies_description', models.TextField(default='', max_length=900)),
                ('movies_time', models.CharField(default='0 minutos', max_length=11)),
                ('movies_category', models.CharField(default='', max_length=50)),
                ('movies_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('is_not_rated', models.BooleanField(default=False)),
            ],
        ),
    ]
