# Generated by Django 5.0.1 on 2024-01-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(default='', max_length=150)),
                ('movie_description', models.TextField(default='', max_length=900)),
                ('movie_time', models.CharField(default='0 minutos', max_length=11)),
                ('movie_category', models.CharField(default='', max_length=50)),
                ('movie_rating', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
