# Generated by Django 5.0.1 on 2024-01-29 21:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_movie_delete_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_year',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
