# Generated by Django 5.0.1 on 2024-01-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_movie_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
